using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Runtime.InteropServices;
using System.Text;
using System.Text.RegularExpressions;
public sealed class CopilotTarget {public int Id,Parent,Session,RootId;public long Created,RootCreated;public string Name,Path,Family,Reason;}
public static class CopilotApp {
 public const string Family="Microsoft.Copilot_8wekyb3d8bbwe";
 [StructLayout(LayoutKind.Sequential,CharSet=CharSet.Unicode)]struct ProcessEntry{public uint size,usage,id;public UIntPtr heap;public uint module,threads,parent;public int priority;public uint flags;[MarshalAs(UnmanagedType.ByValTStr,SizeConst=260)]public string exe;}
 [DllImport("kernel32.dll",SetLastError=true)]static extern IntPtr CreateToolhelp32Snapshot(uint flags,uint id);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool Process32First(IntPtr h,ref ProcessEntry p);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool Process32Next(IntPtr h,ref ProcessEntry p);
 [DllImport("kernel32.dll")]static extern bool ProcessIdToSessionId(uint id,out uint session);
 [DllImport("kernel32.dll",SetLastError=true)]static extern IntPtr OpenProcess(uint access,bool inherit,int id);
 [DllImport("kernel32.dll")]static extern bool CloseHandle(IntPtr h);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode)]static extern int GetPackageFamilyName(IntPtr process,ref uint length,StringBuilder name);
 [DllImport("kernel32.dll",CharSet=CharSet.Unicode,SetLastError=true)]static extern bool QueryFullProcessImageName(IntPtr process,uint flags,StringBuilder name,ref uint size);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool GetProcessTimes(IntPtr h,out long created,out long exit,out long kernel,out long user);
 [DllImport("kernel32.dll",SetLastError=true)]static extern bool TerminateProcess(IntPtr h,uint code);
 [DllImport("kernel32.dll")]static extern uint WaitForSingleObject(IntPtr h,uint timeout);
 static string Package(IntPtr h){uint size=0;int r=GetPackageFamilyName(h,ref size,null);if(r!=122||size==0)return null;var b=new StringBuilder((int)size);return GetPackageFamilyName(h,ref size,b)==0?b.ToString():null;}
 static string Image(IntPtr h){uint size=32768;var b=new StringBuilder((int)size);return QueryFullProcessImageName(h,0,b,ref size)?b.ToString():null;}
 static long Created(IntPtr h){long c,e,k,u;if(!GetProcessTimes(h,out c,out e,out k,out u))throw new Exception("Creation identity unavailable");return c;}
 static bool Host(string name){return name.Equals("explorer",StringComparison.OrdinalIgnoreCase)||name.Equals("RuntimeBroker",StringComparison.OrdinalIgnoreCase)||name.Equals("ApplicationFrameHost",StringComparison.OrdinalIgnoreCase)||name.Equals("msedge",StringComparison.OrdinalIgnoreCase)||name.Equals("dllhost",StringComparison.OrdinalIgnoreCase);}
 public static bool PackagePath(string path,string programFiles){try{string root=System.IO.Path.GetFullPath(programFiles).TrimEnd('\\')+@"\WindowsApps\";string image=System.IO.Path.GetFullPath(path);if(!image.StartsWith(root,StringComparison.OrdinalIgnoreCase))return false;string relative=image.Substring(root.Length);int slash=relative.IndexOf('\\');if(slash<0)return false;return Regex.IsMatch(relative.Substring(0,slash),@"^Microsoft\.Copilot_\d+\.\d+\.\d+\.\d+_(x64|x86|arm64|neutral)__8wekyb3d8bbwe$",RegexOptions.IgnoreCase);}catch{return false;}}
 public static bool DedicatedPath(string image,string programFiles){try{string path=System.IO.Path.GetFullPath(image);string folder=System.IO.Path.Combine(System.IO.Path.GetFullPath(programFiles),@"Microsoft\Copilot\Application");return path.Equals(System.IO.Path.Combine(folder,"mscopilot.exe"),StringComparison.OrdinalIgnoreCase)||path.Equals(System.IO.Path.Combine(folder,"mscopilot_proxy.exe"),StringComparison.OrdinalIgnoreCase);}catch{return false;}}
 static bool TrustedPath(string path){foreach(string root in new[]{Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles),Environment.GetFolderPath(Environment.SpecialFolder.ProgramFilesX86),Environment.GetEnvironmentVariable("ProgramW6432")})if(!String.IsNullOrEmpty(root)&&(PackagePath(path,root)||DedicatedPath(path,root)))return true;return false;}
 public static bool Eligible(string family,string name){return family==Family&&(name.Equals("Copilot",StringComparison.OrdinalIgnoreCase)||name.Equals("Microsoft.Copilot",StringComparison.OrdinalIgnoreCase)||name.Equals("mscopilot_proxy",StringComparison.OrdinalIgnoreCase)||name.Equals("mscopilot",StringComparison.OrdinalIgnoreCase));}
 static bool Root(CopilotTarget p){return !Host(p.Name)&&(Eligible(p.Family,p.Name)||TrustedPath(p.Path));}
 public static List<CopilotTarget> Select(List<CopilotTarget> all,Func<CopilotTarget,bool> root){var result=new List<CopilotTarget>();foreach(var p in all)if(root(p)){p.RootId=p.Id;p.RootCreated=p.Created;p.Reason="Verified standalone Copilot identity/path";result.Add(p);}bool changed;do{changed=false;foreach(var p in all){if(result.Contains(p)||!p.Name.Equals("msedgewebview2",StringComparison.OrdinalIgnoreCase))continue;var parent=result.Find(a=>a.Id==p.Parent&&a.Session==p.Session&&p.Created>=a.Created);if(parent==null)continue;p.RootId=parent.RootId;p.RootCreated=parent.RootCreated;p.Reason="WebView descendant of verified Copilot root #"+p.RootId;result.Add(p);changed=true;}}while(changed);return result;}
 static List<CopilotTarget> Inventory(out string diagnostic){var all=new List<CopilotTarget>();var details=new StringBuilder();int session=Process.GetCurrentProcess().SessionId;IntPtr snapshot=CreateToolhelp32Snapshot(2,0);if(snapshot==new IntPtr(-1))throw new Exception("Native process snapshot failed: "+Marshal.GetLastWin32Error());try{var entry=new ProcessEntry();entry.size=(uint)Marshal.SizeOf(entry);bool more=Process32First(snapshot,ref entry);if(!more)throw new Exception("Native process enumeration failed: "+Marshal.GetLastWin32Error());do{uint sid;if(!ProcessIdToSessionId(entry.id,out sid)||sid!=session)continue;string name=System.IO.Path.GetFileNameWithoutExtension(entry.exe);IntPtr h=OpenProcess(0x1000,false,(int)entry.id);if(h==IntPtr.Zero){if(name.IndexOf("copilot",StringComparison.OrdinalIgnoreCase)>=0||name.Equals("msedgewebview2",StringComparison.OrdinalIgnoreCase))details.AppendLine(name+" #"+entry.id+": access denied/unavailable; not targeted");continue;}try{var p=new CopilotTarget{Id=(int)entry.id,Parent=(int)entry.parent,Session=(int)sid,Name=name,Path=Image(h),Family=Package(h),Created=Created(h)};all.Add(p);if(name.IndexOf("copilot",StringComparison.OrdinalIgnoreCase)>=0||name.Equals("msedgewebview2",StringComparison.OrdinalIgnoreCase)||p.Family==Family||TrustedPath(p.Path))details.AppendLine(name+" #"+p.Id+" parent="+p.Parent+" family="+(p.Family??"unpackaged")+" image="+(p.Path??"unavailable"));}catch(Exception e){details.AppendLine(name+" #"+entry.id+": "+e.Message);}finally{CloseHandle(h);}}while(Process32Next(snapshot,ref entry));int error=Marshal.GetLastWin32Error();if(error!=18&&error!=0)throw new Exception("Process enumeration incomplete: "+error);}finally{CloseHandle(snapshot);}diagnostic="Native snapshot: "+all.Count+" inspectable current-session processes.\r\n"+details;return all;}
 public static List<CopilotTarget> Preview(out string limits){string diagnostics;var all=Inventory(out diagnostics);var targets=Select(all,Root);limits="Current session only. Only verified Copilot roots and their verified WebView descendants are eligible. Shared browser/Office integrations and unverified candidates remain untouched. No continuous relaunch prevention.\r\n\r\n"+diagnostics;return targets;}
 public static string CloseReviewed(List<CopilotTarget> targets){var b=new StringBuilder();string diagnostics;var current=Inventory(out diagnostics);var verified=Select(current,Root);var handles=new Dictionary<int,IntPtr>();try{foreach(var t in targets){var fresh=verified.Find(p=>p.Id==t.Id&&p.Created==t.Created&&p.RootId==t.RootId&&p.RootCreated==t.RootCreated);if(fresh==null){b.AppendLine(t.Name+" #"+t.Id+": exited or identity/ancestry changed; skipped");continue;}IntPtr h=OpenProcess(0x1000|1|0x100000,false,t.Id);if(h==IntPtr.Zero){b.AppendLine(t.Name+" #"+t.Id+": access denied/unavailable");continue;}try{if(Created(h)!=t.Created||!String.Equals(Image(h),fresh.Path,StringComparison.OrdinalIgnoreCase)){CloseHandle(h);b.AppendLine(t.Name+": process identity changed; skipped");continue;}handles[t.Id]=h;}catch(Exception e){CloseHandle(h);b.AppendLine(t.Name+": identity could not be rechecked; "+e.Message);}}foreach(var t in targets){IntPtr h;if(!handles.TryGetValue(t.Id,out h))continue;try{if(WaitForSingleObject(h,0)==0){b.AppendLine(t.Name+" #"+t.Id+": already exited");continue;}if(!TerminateProcess(h,1))throw new Exception("Termination refused: "+Marshal.GetLastWin32Error());b.AppendLine(t.Name+" #"+t.Id+": "+(WaitForSingleObject(h,2000)==0?"exit confirmed":"exit not confirmed"));}catch(Exception e){b.AppendLine(t.Name+" #"+t.Id+": "+e.Message);}}}finally{foreach(var h in handles.Values)CloseHandle(h);}try{string after;var remaining=Preview(out after);if(remaining.Count>0)b.AppendLine("Verified Copilot processes remain/relaunched: "+remaining.Count+". Review again; no complete shutdown claim.");else b.AppendLine("No verified Copilot targets found in follow-up snapshot; unverified integrations remain outside coverage.");}catch(Exception e){b.AppendLine("Follow-up verification failed: "+e.Message);}if(targets.Count==0)b.AppendLine("No verified targets. Use Copilot process diagnostics; this is not proof Copilot is absent.");return b.ToString();}
 public static int Tests(){try{if(!Eligible(Family,"Copilot")||Eligible(Family,"msedgewebview2")||Eligible("Other.Package","Copilot"))throw new Exception("identity");if(!PackagePath(@"C:\Program Files\WindowsApps\Microsoft.Copilot_1.2.3.4_x64__8wekyb3d8bbwe\App\DifferentHost.exe",@"C:\Program Files")||PackagePath(@"C:\Users\x\Microsoft.Copilot_1.2.3.4_x64__8wekyb3d8bbwe\Copilot.exe",@"C:\Program Files")||PackagePath(@"C:\Program Files\WindowsApps\Microsoft.Copilot_1.2.3.4_x64__other\Copilot.exe",@"C:\Program Files"))throw new Exception("package path");if(!DedicatedPath(@"C:\Program Files (x86)\Microsoft\Copilot\Application\mscopilot.exe",@"C:\Program Files (x86)")||!DedicatedPath(@"C:\Program Files (x86)\Microsoft\Copilot\Application\mscopilot_proxy.exe",@"C:\Program Files (x86)")||DedicatedPath(@"C:\Users\x\Microsoft\Copilot\Application\mscopilot.exe",@"C:\Program Files (x86)")||DedicatedPath(@"C:\Program Files (x86)\Microsoft\Copilot\Application\msedge.exe",@"C:\Program Files (x86)")||!Eligible(Family,"mscopilot_proxy")||Eligible(null,"mscopilot"))throw new Exception("reported Copilot variant");var root=new CopilotTarget{Id=1,Session=2,Created=100,Name="Copilot"};var child=new CopilotTarget{Id=2,Parent=1,Session=2,Created=110,Name="msedgewebview2"};var grand=new CopilotTarget{Id=3,Parent=2,Session=2,Created=120,Name="msedgewebview2"};var shared=new CopilotTarget{Id=4,Parent=99,Session=2,Created=120,Name="msedgewebview2"};var browser=new CopilotTarget{Id=5,Parent=1,Session=2,Created=120,Name="msedge"};var stale=new CopilotTarget{Id=6,Parent=1,Session=2,Created=90,Name="msedgewebview2"};var other=new CopilotTarget{Id=7,Parent=1,Session=3,Created=120,Name="msedgewebview2"};var selected=Select(new List<CopilotTarget>{grand,shared,browser,stale,other,root,child},p=>p.Id==1);if(selected.Count!=3||grand.RootCreated!=100||selected.Contains(shared)||selected.Contains(browser))throw new Exception("descendant isolation");var reported=new List<CopilotTarget>();for(int n=0;n<11;n++)reported.Add(new CopilotTarget{Id=100+n,Parent=n>1?101:1,Session=2,Created=200+n,Name=n==0?"mscopilot_proxy":"mscopilot",Path=@"C:\Program Files (x86)\Microsoft\Copilot\Application\"+(n==0?"mscopilot_proxy.exe":"mscopilot.exe")});reported.Add(new CopilotTarget{Id=200,Parent=300,Session=2,Created=500,Name="msedgewebview2",Family="MicrosoftWindows.Client.CBS_cw5n1h2txyewy"});reported.Add(new CopilotTarget{Id=201,Parent=301,Session=2,Created=500,Name="msedgewebview2",Family="MicrosoftWindows.Client.WebExperience_cw5n1h2txyewy"});if(Select(reported,p=>DedicatedPath(p.Path,@"C:\Program Files (x86)")).Count!=11)throw new Exception("reported process tree selection");return 0;}catch{return 1;}}
}


