using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Security.Principal;
using System.Windows.Forms;
public class Window:Form {
 TextBox report=new TextBox{Multiline=true,ReadOnly=true,ScrollBars=ScrollBars.Both,Dock=DockStyle.Fill,Font=new Font("Consolas",10)};
 Button toggle=new Button{Text="Mute microphones / disable cameras",AutoSize=true};
 public static readonly Color Ink=Color.FromArgb(27,25,23),Card=Color.FromArgb(43,39,35),Edge=Color.FromArgb(78,66,54),Orange=Color.FromArgb(255,151,66),Paper=Color.FromArgb(240,232,220),Quiet=Color.FromArgb(189,175,158);
 Panel hintBox; Label hintText;
 Label micState,cameraState,keyState; Button keyToggle; CopilotKeySession keySession; bool preview;
 public Window(){
 Icon=Icon.ExtractAssociatedIcon(Application.ExecutablePath);
  Text="Privacy Switch · Microphone & Camera";ClientSize=new Size(940,730);MinimumSize=new Size(940,740);BackColor=Ink;ForeColor=Paper;Font=new Font("Segoe UI",10);AutoScaleMode=AutoScaleMode.Dpi;StartPosition=FormStartPosition.CenterScreen;
  var root=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(22,18,22,12),ColumnCount=1,RowCount=3};root.RowStyles.Add(new RowStyle(SizeType.Absolute,68));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.Absolute,28));Controls.Add(root);
  var heading=new Panel{Dock=DockStyle.Fill};heading.Controls.Add(LabelAt("PRIVACY SWITCH",0,0,600,27,19,Paper));heading.Controls.Add(LabelAt("Microphone & camera   /   Windows hardware controls",1,34,650,23,10,Quiet));root.Controls.Add(heading,0,0);
  var columns=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=1};columns.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,62));columns.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,38));root.Controls.Add(columns,0,1);
  var left=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=3,Margin=new Padding(0,0,16,0)};left.RowStyles.Add(new RowStyle(SizeType.Absolute,233));left.RowStyles.Add(new RowStyle(SizeType.Absolute,120));left.RowStyles.Add(new RowStyle(SizeType.Percent,100));columns.Controls.Add(left,0,0);
  var current=new Panel{Dock=DockStyle.Fill,BackColor=Card,Padding=new Padding(16),Margin=new Padding(0,0,0,14)};left.Controls.Add(current,0,0);current.Controls.Add(LabelAt("AVAILABLE NOW",16,14,380,20,9,Orange));current.Controls.Add(HelpAt(480,10,"Current microphone & camera controls","CURRENT · Apply uses driver-reported hardware microphone mute and disables supported Camera-class devices. Software-only microphone mute is unsupported. Speakers/shared audio controllers remain untouched. Windows administrator permission is requested only for the reviewed action. Original mute/disabled states are saved before changes and restored later; partial failures retain recovery. Microphone-off can interrupt voice calls. Driver readback is not an end-to-end recording test; live cutoff is still unvalidated."));
  micState=LabelAt("MIC · Checking",16,46,480,25,13,Paper);cameraState=LabelAt("CAM · Checking",16,77,480,25,13,Paper);current.Controls.Add(micState);current.Controls.Add(cameraState);
  current.Controls.Add(LabelAt("Driver readback ≠ validated recording cutoff",16,110,480,20,10,Orange));
  toggle.FlatStyle=FlatStyle.Flat;toggle.FlatAppearance.BorderSize=0;toggle.BackColor=Orange;toggle.ForeColor=Ink;toggle.Font=new Font("Segoe UI",11,FontStyle.Bold);toggle.AutoSize=false;toggle.SetBounds(16,144,480,46);toggle.Anchor=AnchorStyles.Left|AnchorStyles.Right|AnchorStyles.Top;toggle.AccessibleName="Review microphone mute and camera disable or original-state restore";current.Controls.Add(toggle);toggle.Click+=(a,e)=>Action();RegisterHint(toggle,"Review microphone/camera action.\nVoice/video input may stop; admin approval required.");
  current.Controls.Add(LabelAt("Only microphone & camera changes. Restore keeps prior originals.",16,196,480,20,9,Quiet));
  var keyPanel=new Panel{Dock=DockStyle.Fill,BackColor=Card,Margin=new Padding(0,0,0,14)};left.Controls.Add(keyPanel,0,1);keyPanel.Controls.Add(LabelAt("SHORTCUT PROFILE · SESSION ONLY",16,10,440,18,9,Orange));keyPanel.Controls.Add(HelpAt(480,8,"Copilot key shortcut","CURRENT · Block only the exact Left Shift + Left Windows + F23 chord while this app's hook session runs. Extra Ctrl/Alt/right-side modifiers are excluded. It does not disable Copilot, AI, telemetry or other launch methods. F23 release/repeats are tracked consistently during the blocked press. Modifier states are tracked individually and reconciled outside the callback. No typing/history is logged, stored or transmitted. Use Stop key blocking or close the app to remove this session; microphone/camera recovery remains unchanged. No emergency hotkey is installed. Enabling also offers reviewed force-close of identified Microsoft.Copilot app processes in this session. This is a one-time close, not removal or relaunch prevention; unsaved app state cannot be restored. Browser/Office integrations remain outside scope. No autostart or desktop shortcut edits. Hook installation is OS-reported, not a protected-desktop/global keyboard guarantee; Windows can silently remove a timed-out hook. Closing the app removes this session. No admin permission is requested for this profile."));keyState=LabelAt("KEY · Off — no hook installed",16,33,470,18,9,Quiet);keyPanel.Controls.Add(keyState);keyToggle=new Button{Text="Block key + close Copilot app",FlatStyle=FlatStyle.Flat,BackColor=Edge,ForeColor=Paper,Size=new Size(220,32),Location=new Point(16,62),AccessibleName="Toggle session Copilot key chord blocking"};keyPanel.Controls.Add(keyToggle);keyToggle.Click+=(a,e)=>ToggleKey();var inspect=new Button{Text="Inspect Copilot (read-only)",FlatStyle=FlatStyle.Flat,BackColor=Card,ForeColor=Paper,Size=new Size(240,32),Location=new Point(248,62)};keyPanel.Controls.Add(inspect);inspect.Click+=(a,e)=>InspectCopilot();RegisterHint(keyToggle,"Block key chord and review one-time app force-close.\nOther integrations and relaunch remain available.");  var audit=new Panel{Dock=DockStyle.Fill,BackColor=Card,Padding=new Padding(12),Margin=Padding.Empty};left.Controls.Add(audit,0,2);var bar=new Panel{Dock=DockStyle.Top,Height=33};bar.Controls.Add(LabelAt("DEVICE & RECOVERY AUDIT",0,2,300,20,9,Quiet));var refresh=new Button{Text="Refresh",FlatStyle=FlatStyle.Flat,ForeColor=Paper,BackColor=Card,Width=80,Height=27,Dock=DockStyle.Right};refresh.Click+=(a,e)=>RefreshReport();bar.Controls.Add(refresh);report.BackColor=Card;report.ForeColor=Paper;report.BorderStyle=BorderStyle.None;report.WordWrap=true;report.ScrollBars=ScrollBars.Vertical;report.Font=new Font("Consolas",9);audit.Controls.Add(report);audit.Controls.Add(bar);
  var right=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=9,Margin=Padding.Empty};right.RowStyles.Add(new RowStyle(SizeType.Absolute,46));for(int n=0;n<7;n++)right.RowStyles.Add(new RowStyle(SizeType.Absolute,78));right.RowStyles.Add(new RowStyle(SizeType.Percent,100));columns.Controls.Add(right,1,0);var futureHeading=new Panel{Dock=DockStyle.Fill};futureHeading.Controls.Add(LabelAt("PRIVACY PROFILES",0,0,310,23,13,Paper));futureHeading.Controls.Add(LabelAt("Roadmap reminders · help only",0,24,310,18,9,Quiet));right.Controls.Add(futureHeading,0,0);
  string[] titles={"Optional AI access","Background activity","Telemetry reduction","Offline profile","AI hardware & firmware","Platform support","Secure erase / disposal"};
  string[] captions={"Content permissions & feature controls","Data-sharing visibility & limits","Optional, supported diagnostic controls","All applicable local network paths","Inventory first · vendor-specific limits","Linux / macOS validation & backends","Irreversible · information only"};
  string[] help={
   "PLANNED / FUTURE VERSION · Review optional AI feature/service enablement and access to typing, screen/images, content indexing and metadata. Supported permissions, local AI allowlists and cloud connections would be separate controls. This app currently changes none of them. NPU disable cannot remove all AI or stop CPU/GPU computation; local AI need not transmit data. Permissions, originals and reversible paths need platform validation.",
   "PLANNED / FUTURE VERSION · Show supported background activity and data-sharing evidence where available. Silent monitoring is a hypothetical concern, not evidence it is happening. No tool can promise detection of every monitor or prove absence of collection. Current audit only reads microphone/camera controls and driver metadata. Future visibility may require permission and must state coverage/unknowns.",
   "PLANNED / FUTURE VERSION · Review optional telemetry/diagnostic controls supported by each OS edition and app. Explain data flows, save exact originals and report partial failures. No zero-telemetry guarantee. Current app applies no telemetry changes and never turns off Firewall, Defender or OS updates as a privacy measure.",
   "PLANNED / FUTURE VERSION · Review applicable Wi-Fi, Ethernet, cellular, Bluetooth networking, USB and virtual interface paths before local offline restriction. Voice calls/remote access may stop. Administrator permission, exact prior-state restore and hotplug checks would be required. Wi-Fi-only disable is not offline; hostile-administrator-proof isolation is not promised. Current app does not change networking.",
   "PLANNED / FUTURE VERSION · Incomplete AI accelerator inventory and only supported reversible controls. An NPU is not evidence of telemetry. Feature access, chip restriction and firmware are different layers. Vendor firmware may require manual BIOS/UEFI actions and reboot; reliable one-click rollback cannot be assumed. No flashing, security bypass or blind shared-driver unloading. Current app makes no accelerator/firmware changes.",
   "PLANNED / FUTURE VERSION · Broader validated platform profiles. Current Windows app uses hardware microphone mute and camera disable with live cutoff untested. Separate Python source provides unvalidated Linux session mute (cameras unsupported) and macOS detection/permission guidance only. Session mute is not universal hardware cutoff. Same executable does not run everywhere; real target-machine tests are needed.",
   "PLANNED / FUTURE VERSION · INFORMATION ONLY: secure erase for device disposal would be irreversible and separate from reversible privacy profiles. Nothing is erased by this card. Any future workflow needs backup, ownership and exact drive/scope review, staged warnings and explicit final confirmation. An active system drive usually needs a separate recovery/vendor-supported workflow. Infinite overwrites are not valid sanitization: HDD/SSD methods differ, and SSD wear-leveling means repeated logical writes do not guarantee erasure. Future design must consult current NIST SP 800-88 Rev. 2 and vendor sanitize/secure erase/crypto erase capabilities and verification. No universal complete erase, cloud/backups removal or infinite-pass promise. No disk access, destructive commands or execution is implemented."
  };
  for(int n=0;n<7;n++)right.Controls.Add(FutureCard(titles[n],captions[n],help[n]),0,n+1);
  var footer=LabelAt("Windows r2 · controls verified by readback · effective live cutoff remains unvalidated",0,0,880,24,9,Quiet);footer.Dock=DockStyle.Fill;root.Controls.Add(footer,0,2);Shown+=(a,e)=>RefreshReport();
 }
 Label LabelAt(string text,int x,int y,int width,int height,float size,Color color){return new Label{Text=text,Location=new Point(x,y),Size=new Size(width,height),ForeColor=color,Font=new Font("Segoe UI",size),BackColor=Color.Transparent,UseMnemonic=false};}
 Button HelpAt(int x,int y,string title,string body){var b=new Button{Text="?",Location=new Point(x,y),Size=new Size(26,26),FlatStyle=FlatStyle.Flat,ForeColor=Orange,BackColor=Card,AccessibleName="Help: "+title,AccessibleDescription=body};b.FlatAppearance.BorderColor=Edge;RegisterHint(b,"Help: "+title+".\nPress Enter or click for details.");b.Click+=(a,e)=>OpenHelp(title,body);return b;}
 Control FutureCard(string title,string caption,string help){var p=new Panel{Dock=DockStyle.Fill,BackColor=Card,Margin=new Padding(0,0,0,8)};var name=LabelAt(title,12,8,260,22,11,Paper);var state=LabelAt("PLANNED / FUTURE VERSION",12,32,275,17,8,Orange);var desc=LabelAt(caption,12,51,290,17,8,Quiet);p.Controls.Add(name);p.Controls.Add(state);p.Controls.Add(desc);var q=HelpAt(285,7,title,help);q.Anchor=AnchorStyles.Top|AnchorStyles.Left;p.Controls.Add(q);p.SizeChanged+=(a,e)=>q.Location=new Point(p.ClientSize.Width-38,7);string brief="Planned / future version.\nClick ? for "+title.ToLowerInvariant()+" details.";RegisterHint(p,brief);RegisterHint(name,brief);RegisterHint(state,brief);RegisterHint(desc,brief);name.Click+=(a,e)=>q.PerformClick();p.AccessibleName=title+" planned, help only";return p;}
 void UpdateKeyState(){if(IsDisposed||Disposing)return;bool installed=keySession!=null&&keySession.Installed;keyToggle.Text=installed?"Stop key blocking":"Block key + close Copilot app";keyState.Text=installed?"KEY · Hook installed (OS reported) · session only":keySession!=null&&keySession.Error!=null?"KEY · Failed / stopped — see help or retry":"KEY · Off — no hook installed";}
 void InspectCopilot(){HideHint();if(preview)return;try{string diagnostic;var targets=CopilotApp.Preview(out diagnostic);var text=new System.Text.StringBuilder();text.AppendLine("Verified targets: "+targets.Count);foreach(var target in targets)text.AppendLine(target.Name+" #"+target.Id+" | "+target.Reason);text.AppendLine(diagnostic);using(var dialog=new HelpDialog("Copilot process diagnostics · read-only",text.ToString()))dialog.ShowDialog(this);}catch(Exception e){MessageBox.Show(this,e.Message,"Copilot diagnostics failed");}}
 void ToggleKey(){if(preview)return;HideHint();try{if(keySession!=null&&keySession.Installed){keySession.Dispose();keySession=null;}else{string limits;List<CopilotTarget> targets;try{targets=CopilotApp.Preview(out limits);}catch(Exception detection){targets=new List<CopilotTarget>();limits="Copilot detection failed: "+detection.Message+". Only key blocking can be enabled; no process termination will be attempted.";}var review=new System.Text.StringBuilder();foreach(var target in targets)review.AppendLine(target.Name+" #"+target.Id+" | "+target.Reason);using(var confirmation=new HelpDialog("Review Copilot app close","Enable key blocking and force-close these verified Copilot processes? Unsaved app state may be lost and cannot be restored. Only reviewed identities will be targeted.\r\n\r\n"+review+"\r\n"+limits,true)){if(confirmation.ShowDialog(this)!=DialogResult.OK)return;}string closed=targets.Count==0?"No verified Copilot targets; no process was force-closed. Key blocking can still run. Use Inspect Copilot for details.":CopilotApp.CloseReviewed(targets);using(var results=new HelpDialog("Copilot close results",closed+"\r\n"+limits))results.ShowDialog(this);if(keySession!=null){keySession.Dispose();keySession=null;}keySession=new CopilotKeySession();keySession.Changed+=()=>{if(IsHandleCreated&&!IsDisposed)try{BeginInvoke((Action)UpdateKeyState);}catch{}};keySession.Start();}}catch(Exception e){MessageBox.Show(this,e.Message,"Copilot key profile",MessageBoxButtons.OK,MessageBoxIcon.Warning);}UpdateKeyState();}
 void StopKey(){if(keySession==null)return;keySession.Dispose();keySession=null;} void RegisterHint(Control target,string brief){target.MouseEnter+=(a,e)=>ShowHint(target,brief);target.MouseLeave+=(a,e)=>HideHint();target.Enter+=(a,e)=>ShowHint(target,brief);target.Leave+=(a,e)=>HideHint();target.Disposed+=(a,e)=>HideHint();}
 void ShowHint(Control target,string brief){if(IsDisposed||Disposing||!ContainsFocus)return;if(hintBox==null){hintBox=new Panel{BackColor=Edge,Size=new Size(340,68),Padding=new Padding(10),Visible=false,TabStop=false};hintText=new Label{Dock=DockStyle.Fill,ForeColor=Paper,BackColor=Edge,Font=new Font("Segoe UI",9),UseMnemonic=false,AutoSize=false,TextAlign=ContentAlignment.MiddleLeft};hintBox.Controls.Add(hintText);Controls.Add(hintBox);}hintText.Text=brief;Point point=PointToClient(target.PointToScreen(new Point(0,target.Height+4)));point.X=Math.Max(8,Math.Min(point.X,ClientSize.Width-hintBox.Width-8));point.Y=Math.Max(8,Math.Min(point.Y,ClientSize.Height-hintBox.Height-8));hintBox.Location=point;hintBox.Visible=true;hintBox.BringToFront();}
 void HideHint(){if(hintBox!=null&&!hintBox.IsDisposed)hintBox.Visible=false;}
 void OpenHelp(string title,string body){HideHint();try{using(var help=new HelpDialog(title,body)){help.ShowDialog(this);}}finally{HideHint();}}
 protected override void OnDeactivate(EventArgs e){HideHint();base.OnDeactivate(e);}
 protected override void OnResize(EventArgs e){HideHint();base.OnResize(e);}
 protected override void OnFormClosing(FormClosingEventArgs e){HideHint();try{StopKey();}catch(Exception x){if(!preview)MessageBox.Show(this,x.Message,"Hook shutdown",MessageBoxButtons.OK,MessageBoxIcon.Warning);}base.OnFormClosing(e);}
 protected override void Dispose(bool disposing){if(disposing){HideHint();try{StopKey();}catch{}}base.Dispose(disposing);} void UpdateSummary(){try{var capture=Engine.Capture();var active=capture.FindAll(a=>a.State==1);bool unsupported=false,unmuted=false;foreach(var a in active){unsupported|=(Engine.Hardware(a.Id)&2)==0;unmuted|=!Engine.Muted(a.Id);}micState.Text=active.Count==0?"MIC · No active capture endpoint":unsupported?"MIC · Unsupported hardware mute":unmuted?"MIC · Available / not hardware-muted":"MIC · Hardware mute confirmed by driver";micState.ForeColor=unmuted||unsupported?Orange:Paper;}catch{micState.Text="MIC · Verification unavailable";micState.ForeColor=Orange;}try{var cameras=Engine.Inventory().FindAll(d=>d.Class=="Camera");cameraState.Text=cameras.Count==0?"CAM · No supported camera found":cameras.Exists(d=>d.Problem==0)?"CAM · Camera enabled":cameras.TrueForAll(d=>d.Problem==22)?"CAM · Disabled status confirmed":"CAM · Partial / driver issue";}catch{cameraState.Text="CAM · Verification unavailable";}if(preview){Text="Privacy Switch · SIMULATED UI PREVIEW";report.Text="SIMULATED PREVIEW — no device changes\r\n\r\n"+report.Text;}}
 static Button FindHelp(Control root,string name){foreach(Control child in root.Controls){var button=child as Button;if(button!=null&&button.AccessibleName==name)return button;var found=FindHelp(child,name);if(found!=null)return found;}return null;}
 public static int VerifyHelpLayout(){try{string folder=Path.Combine(Environment.CurrentDirectory,"work");Directory.CreateDirectory(folder);RenderPreview(Path.Combine(folder,"ui-test.png"));using(var w=new Window()){w.preview=true;w.Opacity=0;w.ShowInTaskbar=false;w.Show();Application.DoEvents();var eraseHelp=FindHelp(w,"Help: Secure erase / disposal");if(eraseHelp==null||!eraseHelp.AccessibleDescription.Contains("INFORMATION ONLY")||!eraseHelp.AccessibleDescription.Contains("irreversible"))throw new Exception("Planned erase help missing");w.ShowHint(w.toggle,"Planned / future version.\nClick ? for bounded details.");if(w.hintBox==null)throw new Exception("Hint not constructed");if(w.hintBox.Width>340||w.hintBox.Height>68||!w.ClientRectangle.Contains(w.hintBox.Bounds))throw new Exception("Hint exceeds app bounds");w.OnDeactivate(EventArgs.Empty);if(w.hintBox.Visible)throw new Exception("Deactivate did not hide hint");w.ShowHint(w.toggle,"Short focus hint");w.OnResize(EventArgs.Empty);if(w.hintBox.Visible)throw new Exception("Resize did not hide hint");w.ShowHint(w.toggle,"Short close hint");w.OnFormClosing(new FormClosingEventArgs(CloseReason.UserClosing,false));if(w.hintBox.Visible)throw new Exception("Closing did not hide hint");using(var help=new HelpDialog("Optional AI access",new string('x',4000))){help.Owner=w;if(help.ClientSize.Width>600||help.ClientSize.Height>440)throw new Exception("Help bounds");if(!help.Details.WordWrap||help.Details.ScrollBars!=ScrollBars.Vertical)throw new Exception("Full help does not wrap/scroll");if(help.Owner!=w||help.CancelButton==null)throw new Exception("Help ownership/escape");help.Opacity=0;help.ShowInTaskbar=false;help.Show();Application.DoEvents();using(var bitmap=new Bitmap(help.Width,help.Height)){help.DrawToBitmap(bitmap,new Rectangle(Point.Empty,help.Size));bitmap.Save(Path.Combine(folder,"help-layout-test.png"));}help.Close();}Panel hint=w.hintBox;using(var owned=new HelpDialog("Owner close test","Bounded owned help")){owned.Opacity=0;owned.ShowInTaskbar=false;owned.Show(w);Application.DoEvents();w.Dispose();if(!owned.IsDisposed)throw new Exception("Owned help survived app disposal");}if(!hint.IsDisposed)throw new Exception("Hint survived owner disposal");}return 0;}catch(Exception x){File.WriteAllText(Path.Combine(Environment.CurrentDirectory,"work","ui-test-error.txt"),x.ToString());return 1;}}

 public static int RenderPreview(string path){Application.EnableVisualStyles();Engine.Root=Path.Combine(Environment.CurrentDirectory,"work","ui-preview-unused");Engine.Inventory=()=>new List<Device>{new Device{Id="camera-example",Name="Integrated Camera (example)",Class="Camera",Problem=0,Selected=true,Manufacturer="Example driver",Driver="UI simulation"},new Device{Id="SWD\\MMDEVAPI\\{0.0.1.00000000}.example",Name="Microphone Array (example)",Class="AudioEndpoint",Problem=0,Selected=true,Manufacturer="Example driver",Driver="UI simulation"}};Engine.Capture=()=>new List<CaptureState>{new CaptureState{Id="{0.0.1.00000000}.example",State=1}};Engine.Hardware=id=>3;Engine.Muted=id=>false;using(var w=new Window()){w.preview=true;w.ShowInTaskbar=false;w.Opacity=0;w.Show();Application.DoEvents();w.RefreshReport();w.PerformLayout();using(var bitmap=new Bitmap(w.Width,w.Height)){w.DrawToBitmap(bitmap,new Rectangle(Point.Empty,w.Size));bitmap.Save(path,System.Drawing.Imaging.ImageFormat.Png);}}return 0;}

 void RefreshReport(){toggle.Text=File.Exists(Engine.FilePath)?"Restore original mic / camera states":"Mute microphones / disable cameras";var b=new System.Text.StringBuilder();b.AppendLine("MICROPHONE & CAMERA SWITCH — Windows backend r2\r\n");b.AppendLine("OS: "+Compatibility.OS()+"\r\n");b.AppendLine("Hardware microphone mute and supported camera disable only.");b.AppendLine("Microphone mute is verified by driver readback; effective recording cutoff remains UNTESTED.");b.AppendLine("Restore preserves prior mute and disabled states. Software-only microphone mute is unsupported.");b.AppendLine("Review targets below. Administrator permission is requested for changes.\r\n");b.AppendLine("Legacy Image-class devices are listed for review, not automatically disabled.");try{foreach(var d in Engine.Inventory())if(d.Selected||d.Class=="Image")b.AppendLine((d.Selected?"TARGET  ":"UNSUPPORTED / REVIEW  ")+d.Name+" | "+d.Class+" | "+(d.Problem==22?"disabled":d.Problem==0?"enabled":"problem "+d.Problem)+"\r\n        "+d.Id+"\r\n        Driver: "+d.Manufacturer+" | "+d.Driver);}catch(Exception x){b.AppendLine("INVENTORY FAILED: "+x.Message);}try{b.AppendLine("\r\nREAD-ONLY AUDIO DRIVER METADATA (shared controllers are never changed)");foreach(var d in Engine.Inventory())if(d.Class.Equals("MEDIA",StringComparison.OrdinalIgnoreCase))b.AppendLine(d.Name+" | "+d.Manufacturer+" | "+d.Driver);}catch(Exception x){b.AppendLine("Driver metadata unavailable: "+x.Message);}try{b.AppendLine("\r\nCORE AUDIO CAPTURE AUDIT");foreach(var a in Engine.Capture()){if(a.State!=1){b.AppendLine(a.Id+" | "+CoreAudio.Describe(a.State)+" | skipped (inactive)");continue;}uint mask=Engine.Hardware(a.Id);b.AppendLine(a.Id+" | "+CoreAudio.Describe(a.State)+" | hardware support mask="+mask+" | "+((mask&2)==0?"UNSUPPORTED hardware mute":Engine.Muted(a.Id)?"driver reports hardware-muted; live cutoff unverified":"NOT MUTED; capture available"));}}catch(Exception x){b.AppendLine("CORE AUDIO VERIFICATION FAILED: "+x.Message);}if(File.Exists(Engine.FilePath))try{b.AppendLine("\r\nRECOVERY AUDIT (restrictions may be partial)");foreach(var e in Engine.Load().Entries)b.AppendLine(e.Name+": "+e.Result+" | restore pending="+e.Pending);}catch(Exception x){b.AppendLine("RECOVERY ERROR: "+x.Message);}report.Text=b.ToString();UpdateSummary();}
 void Action(){if(preview)return;bool restore=File.Exists(Engine.FilePath);if(MessageBox.Show(restore?"Restore recorded microphone and camera original states?":"Apply hardware microphone mute and camera disable? Voice/video input may stop. Shared audio controllers stay untouched. Live capture cutoff must be tested; no protected status is claimed.","Review device action",MessageBoxButtons.OKCancel,MessageBoxIcon.Warning)!=DialogResult.OK)return;try{var p=Process.Start(new ProcessStartInfo(Application.ExecutablePath,restore?"--restore":"--apply"){UseShellExecute=true,Verb="runas"});p.WaitForExit();if(p.ExitCode!=0)MessageBox.Show("Action failed or was partial. Review the audit.");}catch(Exception x){MessageBox.Show(x.Message);}RefreshReport();}
 [STAThread] public static int Main(string[] args){if(args.Length>0&&args[0]=="--test-app")return CopilotApp.Tests();if(args.Length>0&&args[0]=="--test-key")return CopilotKeyTests.Run();if(args.Length>0&&args[0]=="--test-ui")return VerifyHelpLayout();if(args.Length==2&&args[0]=="--preview")return RenderPreview(args[1]);if(args.Length>0&&args[0]=="--test")return Tests.Run();if(args.Length>0){if(!new WindowsPrincipal(WindowsIdentity.GetCurrent()).IsInRole(WindowsBuiltInRole.Administrator))return 2;try{using(var gate=new System.Threading.Mutex(false,@"Global\PrivacySwitchDeviceAction")){if(!gate.WaitOne(0))throw new Exception("Another device action is running");try{if(args[0]=="--apply")Engine.Apply();else if(args[0]=="--restore")Engine.Restore();else return 3;}finally{gate.ReleaseMutex();}}if(File.Exists(Engine.FilePath)){var j=Engine.Load();if(args[0]=="--restore"||j.Entries.Exists(e=>!e.Done))return 4;}return 0;}catch(Exception x){MessageBox.Show(x.Message,"Device helper");return 1;}}Application.EnableVisualStyles();Application.Run(new Window());return 0;}
}






public sealed class HelpDialog:Form {
 public readonly TextBox Details;
 public HelpDialog(string title,string body,bool confirm=false){Text="Privacy Switch · "+title;BackColor=Window.Ink;ForeColor=Window.Paper;ClientSize=new Size(560,390);FormBorderStyle=FormBorderStyle.FixedDialog;MaximizeBox=false;MinimizeBox=false;ShowInTaskbar=false;StartPosition=FormStartPosition.CenterParent;Font=new Font("Segoe UI",10);AutoScaleMode=AutoScaleMode.Dpi;var area=Screen.FromPoint(Cursor.Position).WorkingArea;ClientSize=new Size(Math.Min(560,Math.Max(280,area.Width-80)),Math.Min(390,Math.Max(240,area.Height-100)));var root=new TableLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(18),ColumnCount=1,RowCount=3};root.RowStyles.Add(new RowStyle(SizeType.Absolute,46));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.Absolute,46));Controls.Add(root);root.Controls.Add(new Label{Text=title,ForeColor=Window.Orange,Font=new Font("Segoe UI",15),Dock=DockStyle.Fill,UseMnemonic=false},0,0);Details=new TextBox{Text=body,Multiline=true,ReadOnly=true,WordWrap=true,ScrollBars=ScrollBars.Vertical,Dock=DockStyle.Fill,BackColor=Window.Card,ForeColor=Window.Paper,BorderStyle=BorderStyle.None,AccessibleName=title+" help details"};root.Controls.Add(Details,0,1);var close=new Button{Text="Close",DialogResult=DialogResult.Cancel,BackColor=Window.Orange,ForeColor=Window.Ink,FlatStyle=FlatStyle.Flat,Size=new Size(96,32),Anchor=AnchorStyles.Right|AnchorStyles.Bottom};var buttons=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(0,10,0,0)};buttons.Controls.Add(close);if(confirm){close.Text="Cancel";var apply=new Button{Text="Enable key + close app",DialogResult=DialogResult.OK,BackColor=Window.Orange,ForeColor=Window.Ink,FlatStyle=FlatStyle.Flat,Size=new Size(205,32)};buttons.Controls.Add(apply);}root.Controls.Add(buttons,0,2);CancelButton=close;AcceptButton=close;}
}










